
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COLON DATE FLOAT INT KEY MINUS RANGElines : line\n             | lines lineline : KEY COLON valuevalue : FLOAT\n             | INT\n             | DATE\n             | DATE RANGE DATE\n             | exprexpr : value AND value\n            | value MINUS value'
    
_lr_action_items = {'KEY':([0,1,2,4,6,7,8,9,10,14,15,16,],[3,3,-1,-2,-3,-4,-5,-6,-8,-9,-10,-7,]),'$end':([1,2,4,6,7,8,9,10,14,15,16,],[0,-1,-2,-3,-4,-5,-6,-8,-9,-10,-7,]),'COLON':([3,],[5,]),'FLOAT':([5,11,12,],[7,7,7,]),'INT':([5,11,12,],[8,8,8,]),'DATE':([5,11,12,13,],[9,9,9,16,]),'AND':([6,7,8,9,10,14,15,16,],[11,-4,-5,-6,-8,11,11,-7,]),'MINUS':([6,7,8,9,10,14,15,16,],[12,-4,-5,-6,-8,12,12,-7,]),'RANGE':([9,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lines':([0,],[1,]),'line':([0,1,],[2,4,]),'value':([5,11,12,],[6,14,15,]),'expr':([5,11,12,],[10,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lines","S'",1,None,None,None),
  ('lines -> line','lines',1,'p_lines','example.py',61),
  ('lines -> lines line','lines',2,'p_lines','example.py',62),
  ('line -> KEY COLON value','line',3,'p_line','example.py',66),
  ('value -> FLOAT','value',1,'p_value','example.py',70),
  ('value -> INT','value',1,'p_value','example.py',71),
  ('value -> DATE','value',1,'p_value','example.py',72),
  ('value -> DATE RANGE DATE','value',3,'p_value','example.py',73),
  ('value -> expr','value',1,'p_value','example.py',74),
  ('expr -> value AND value','expr',3,'p_expr','example.py',78),
  ('expr -> value MINUS value','expr',3,'p_expr','example.py',79),
]
